### ISSUE TITLE
ROS & PCL - Spherical Coordinates Fails and the ROS process dies - issue

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#3]
@miguelriemoliveira me and  @tiagomfmadeira developed a function that computes the spherical coordinates in order to determine an angle theta using the cartesian coordinates from the point cloud. The code can be seen here:
![image](https://user-images.githubusercontent.com/22821533/58135425-5cd97c00-7c22-11e9-83e5-feaf7f8f8439.png)
But for whatever reason the ROS node does not pass from the first calculation and the process simply dies.
![image](https://user-images.githubusercontent.com/22821533/58135479-9a3e0980-7c22-11e9-8221-afeb27390202.png)
Do you have any idea why this might happen?

Thank you in advance.
Pedro Silva - 72645

**Comment by tiagomfmadeira** [comment]
@miguelriemoliveira For a bit of context here:

The first idea was to create a transformation matrix that would perform the conversion from Cartesian coordinates to Spherical coordinates and simply apply the transformation to the point cloud. But, since the filtering of each point was being done by iteration of the point cloud, might as well simplify the calculations! For now anyway....

The point coordinates had to be converted from OpenGL to OpenCV to make sense. :) Then we figured we'd filter the results based on θ (the azimuthal angle). Since it seems to give us what we want, see figure:

![image](https://user-images.githubusercontent.com/15963210/58136425-e2aaf680-7c25-11e9-99ee-95beb5e9a74a.png)

0≤θ<2π and rotates around the z axis, which makes sense (unless I'm missing more tricky conversions between formats)
[\*Cool interactive simulation\*](https://mathinsight.org/spherical_coordinates)

The result of the calculation was validated through an online calculator, and as such I don't believe that's where the problem lies.

Maybe the exporting or loading of the new pointcloud by rviz... Not sure here...
I've suggested that @SIlvaMFPedro should use the filter at θ≥0 & θ<2π and check whether the whole point cloud is there, then experiment with different ranges to see what comes up. But this seems to not be possible right now because of this bug he's describing.

**Comment by miguelriemoliveira** [comment]
Hi,

@SIlvaMFPedro please don't copy paste code. Just refer the file of code line you want like this:

https://github.com/lardemua/ros_bridge/blob/54a7c7b7d544fafafc979602b5dd99ba50272735/carla_ros_pcl_filter/src/PclFilter.cpp#L58

Without being able to review all the details, your explanations about spherical coordinates make sense in general and that's the idea.

But notice that the points you receive must be in the sensor reference frame so that the transformation (and filtering) to spherical coordinates works. Can you run:

```bash
rostopic echo <yout point cloud topic> | grep frame_id
```

what is the result? Is it the sensor reference frame?

Another route which I suggested is to use the simulator configuration to limit the range of the lasers, this should be possible. Where is / are your configuration file(s)? I can try to take a look ...

**Comment by SIlvaMFPedro** [comment]
Good morning,
@miguelriemoliveira if i run the previous command with https://github.com/lardemua/ros_bridge/blob/54a7c7b7d544fafafc979602b5dd99ba50272735/carla_ros_pcl_filter/src/PclFilter.cpp#L245 callback function it will not show anything because the process dies before publishing the message into the new ROS topic.
I reference the frame ID in the transformation in this line:
https://github.com/lardemua/ros_bridge/blob/54a7c7b7d544fafafc979602b5dd99ba50272735/carla_ros_pcl_filter/src/PclFilter.cpp#L258
and i reference the frame ID again when i want to publish the new PointCloud2 message into the new ROS topic in this line:
https://github.com/lardemua/ros_bridge/blob/54a7c7b7d544fafafc979602b5dd99ba50272735/carla_ros_pcl_filter/src/PclFilter.cpp#L296-L298.
However if i use any other callback function and run: 

rostopic echo /carla/ego_vehicle/lidar/front/new_point_cloud | grep frame_id

it references the frame_id of the subscriber topic: 
![image](https://user-images.githubusercontent.com/22821533/58163580-29c3d680-7c7c-11e9-8dc1-82448f144ead.png)

I don't change the limit range of the lasers directly in the simulator i do so using a sensor configuration file https://github.com/lardemua/ros_bridge/blob/master/carla_ros_vehicle/config/sensors.json before running the vehicle node. 
I specify the range of each one of the LIDAR sensors in that file which in the case of CARLA, corresponds to the maximum measurement distance in centimeters.

**Comment by miguelriemoliveira** [comment]
Hi @SIlvaMFPedro 

> callback function it will not show anything because the process dies before publishing the message into the new ROS topic.

it dies? Is that not a problem? Why does it die?

**Comment by miguelriemoliveira** [comment]
Concerning :

> I don't change the limit range of the lasers directly in the simulator i do so using a sensor configuration file https://github.com/lardemua/ros_bridge/blob/master/carla_ros_vehicle/config/sensors.json before running the vehicle node.
> I specify the range of each one of the LIDAR sensors in that file which in the case of CARLA, corresponds to the maximum measurement distance in centimeters.

I looked into the manuals of Carla and I think they don't have the possibility to represent 2D lidars, so only your solution seems possible.

**Comment by SIlvaMFPedro** [comment]
> Hi @SIlvaMFPedro
> 
> > callback function it will not show anything because the process dies before publishing the message into the new ROS topic.
> 
> it dies? Is that not a problem? Why does it die?

The process dies when it starts calculating the spherical coordinates. I think it might be an overflow problem because of the number of points of the point cloud.
I am currently trying with fewer points to figure out when the overflow happens and the process dies.

**Comment by miguelriemoliveira** [comment]
On which line does it crash?

**Comment by SIlvaMFPedro** [comment]
the process crashes in this for cycle:
https://github.com/lardemua/ros_bridge/blob/affdd111cbef355af19bb0ddd7f5e9b78fdc16c0/carla_ros_pcl_filter/src/PclFilter.cpp#L278

**Comment by miguelriemoliveira** [comment]
The problem I think is because you have allocated no space of the vector points in your output cloud point cloud. 

I think you must make sure that you have a vector points in your output cloud of the same size as the vector points in your transformedCloudPtr.

Try to use std::vector resize () as follows:

```cpp
PointCloud<PointXYZ>::Ptr outputCloud (new PointCloud<PointXYZ>);
outputCloud->points.resize(transformedCloudPtr->points.size());
```

Or you can just do a copy of the transformedCloudPtr and then you are sure it has the same size:
```cpp
PointCloud<PointXYZ>::Ptr outputCloud (new PointCloud<PointXYZ>);
*outputCloud = *transformedCloudPtr;
```

Tell me if it worked ...

**Comment by SIlvaMFPedro** [comment]
Good afternooon.
It works yes.
Thank you very much.

**Comment by SIlvaMFPedro** [comment]
@miguelriemoliveira Funny with a theta angle between [ π/2,  π +  π/2] the point cloud that should be horizontal shows up as vertical in RVIZ o.O
![Screenshot from 2019-05-22 14-44-54](https://user-images.githubusercontent.com/22821533/58179732-ab2d6000-7ca0-11e9-8b0b-87f489d83e04.png)

Is it because it is missing the rotation/orientation of the points?

**Comment by miguelriemoliveira** [comment]
Which one worked?

About your question, notice you are changing the coordinates here 

https://github.com/lardemua/ros_bridge/blob/affdd111cbef355af19bb0ddd7f5e9b78fdc16c0/carla_ros_pcl_filter/src/PclFilter.cpp#L283

and here

https://github.com/lardemua/ros_bridge/blob/affdd111cbef355af19bb0ddd7f5e9b78fdc16c0/carla_ros_pcl_filter/src/PclFilter.cpp#L284

that should be the problem ...

**Comment by SIlvaMFPedro** [comment]
i used the first approach:
https://github.com/lardemua/ros_bridge/blob/205cb9ed4c3abde609050c66092fad749cd06557/carla_ros_pcl_filter/src/PclFilter.cpp#L269-L271

I also fixed the coordinates issue in RVIZ and here is the result with a theta angle between 0 and π:
![image](https://user-images.githubusercontent.com/22821533/58208838-8a373000-7cdd-11e9-806f-9721fce00a31.png)

I am noticing an issue right now because some of the points near the vehicle are not being showned in RVIZ.

I will continue to test the results with other angles to see if the problem lies in the filtering or it just a problem in the sensor configuration.

Thank you very much ;)

**Comment by miguelriemoliveira** [comment]
Great! No problem.
